// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Conexión DIRECTA (puerto 5432, sin pgbouncer) — la usan `prisma migrate` /
  // `db push` / `studio`. Prisma Client en runtime usa DATABASE_URL (pooled)
  // por separado, vía el adapter en src/lib/prisma.ts.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
